# this file will hold the lists and dictionaries that store the keywords
# for food types and special room names (non-numbers).


# for roomKeywords, the keys are words that might be found in emails, and the actual values are the room names that will
# be inserted to the DB
roomKeywords = {'kresge':'kresge',
                'w20': 'W20',
                'verdes': 'W20',
                ' stud ': 'W20',
                'student center': 'W20',
                'student centre': 'W20',
                'stata': 'Stata',
                'simmons': 'simmons',
                'macgregor': 'macgregor',
                'baker': 'baker',
                'next': 'next',
                'maseeh': 'maseeh',
                'steam cafe': 'Steam Cafe',
                'walker': 'Walker Memorial',
                'lobby 7': 'Lobby 7',
                'lobby 10': 'Lobby 10',
                'killian court': 'Killian Court',
                'killian hall': 'Killian Hall',
                'forbes cafe': 'Forbes Cafe',
                'hayden': 'Hayden Library',
                'lobdell': 'Lobdell',
                'eastman': 'Eastman Court',
                'la sala': 'La Sala de Puerto Rico',
                'morss hall': 'Morss Hall',
                }
# add all the building numbers from 1 to 80
for i in range (1,81):
    roomKeywords['building '+str(i)] = 'Building '+ str(i)



foodKeywords = ['wrap',
                'thai',
                'beef', 
                'rice', 
                'salad', 
                'popcorn',
                'mexican',
                'mac and cheese',
                'mac & cheese',
                'subway',
                'sandwich',
                'chicken',
                'asian',
                'pizza',
                'pasta',
                'pulled pork',
                'pork',
                'indian',
                'lamb',
                'naan',
                'chinese',
                'burger',
                'corn',
                'potato',
                'greek',
                'vegetables',
                'humus',
                'hummus',
                'muffins',
                'sides',
                'fried chicken',
                'italian',
                'israeli',
                'pita',
                'masala',
                'apples', 'avacado', 'alfalfa', 'acorn', 'squash', 'almond', 'arugala', 'artichoke', 'applesauce', 'asian', 'noodles',
        'ahi', 'tuna', 'apple', 'juice', 'avocado', 'roll', 'bruscetta', 
        'black', 'bagels', 'baked', 'beans', 'bbq', 'bison', 'barley', 'beer', 'bisque', 'bluefish', 'bread',
        'broccoli', 'buritto', 'babaganoosh', 'cabbage', 'cake', 'carrots', 'carne', 'asada', 'celery', 'cheese',
        'catfish', 'chips', 'chocolate', 'chowder', 'clams', 'coffee', 'cookies', 'corn', 'cupcakes', 'crab',
        'curry', 'cereal', 'chimichanga', 'dates', 'dips', 'duck', 'dumplings', 'donuts', 'eggs', 'enchilada',
        'eggrolls', 'english', 'muffins', 'edimame', 'eel', 'sushi', 'fajita', 'falafel', 'fish',
        'franks', 'fondu', 'french', 'toast', 'french', 'dip', 'garlic', 'ginger', 'gnocchi', 'goose', 'granola',
        'grapes', 'green', 'guancamole', 'gumbo', 'grits', 'graham', 'crackers', 'ham', 'halibut', 'hamburger',
        'cheeseburgers', 'bacon', 'cheeseburgers', 'honey', 'huenos', 'rancheros', 'hash', 'browns',
        'hot', 'dogs', 'haiku', 'roll', 'hummus', 'ice', 'cream', 'irish', 'stew', 'indian', 'italian', 'bread',
        'jambalaya', 'jelly', 'jerky', 'jalapeo', 'kale', 'kabobs', 'ketchup', 'kiwi', 'kidney', 'kingfish',
        'lobster', 'lamb', 'linguine', 'lasagna', 'meatballs', 'moose', 'milk', 'milkshake', 'noodles', 'ostrich',
        'pizza', 'pepperoni', 'porter', 'pancakes', 'quesadilla', 'quiche', 'reuben', 'spinach', 'spaghetti', 'tater',
        'tots', 'toast', 'ideas', 'venison', 'waffles', 'wine', 'walnuts', 'wildcard', 'day', 'ziti', 'zucchini']
